spring:
  application:
    name: quizz
  data:
    mongodb:
      host: localhost
      port: 62344
      database: quizz
      username: root
      password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://id.twitch.tv/oauth2/token
      client:
        registration:
          twitch:
            client-id: s3y64z1wfc17jpb06vcxkpvyccr3pa
            client-secret: hl5mcgshgjhmbd7uup539z0bienext
            client-authentication-method: client_secret_post
            scope:
              - bits:read
              - moderator:read:followers
              - channel:read:subscriptions
              - user:read:subscriptions
              - channel:read:redemptions
              - channel:manage:redemptions
            redirect-uri: http://localhost:8080/login/oauth2/code/twitch
            provider: twitch
            authorization-grant-type: authorization_code
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://id.twitch.tv/oauth2/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://id.twitch.tv/oauth2/keys
